# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install 
      run: npm install --legacy-peer-deps
    - name: build
      run:  npm run build
    - name: git clone
      run:  |
        git clone https://github.com/1574242600/1574242600.github.io.git .deploy_git
        cd .deploy_git 
        git checkout main
        cd ../
    - name: commit files
      run: |
        mv .deploy_git/.git ./public/
        cd ./public/
        git config user.name "1574242600"
        git config user.email "1574242600@qq.com"
        git add . 
        git commit -m " Github Actions `date +"%Y-%m-%d %H:%M"`" -n
    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        directory: ./public/
